name: Tests
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:

  tests:
    name: ✅ Run tests
    runs-on: ${{ "{{" }} matrix.os {{ "}}" }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ "{{" }} matrix.python-version {{ "}}" }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ "{{" }} matrix.python-version {{ "}}" }}

    - name: Install dependencies
      run: |
        pipx install hatch

    - name: Test with coverage
      run: |
        hatch run test


  codeql:
    name: 🔎 CodeQL analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write # required for all workflows
      # only required for workflows in private repositories:
      actions: read
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: python

      # Autobuild attempts to build any compiled languages (C/C++, C#, Go, or Java)
      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

{% if cookiecutter.documentation_website|lower != "no" %}
  publish-docs:
    name: 📖 Update documentation website
    if: github.ref == 'refs/heads/main'
    needs: [tests, CodeQL-Analysis]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install ".[doc]"

      - name: Deploy mkdocs on GitHub Pages
        env:
          GITHUB_TOKEN: ${{ "{{" }} secrets.GITHUB_TOKEN {{ "}}" }}
        run: |
          mkdocs gh-deploy
{% endif %}