# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-added-large-files
      name: " 🐘 Check for added large files"
    - id: check-toml
      name: " ✔️  Check TOML"
    - id: check-yaml
      name: " ✔️  Check YAML"
      args:
      - --unsafe
    - id: check-json
      name: " ✔️  Check JSON"
    - id: end-of-file-fixer
      name: " 🪚 Fix end of files"
    - id: trailing-whitespace
      name: " ✂️  Trim trailing whitespaces"
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: " ✒️  Formatting code with Black"
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.277
    hooks:
      - id: ruff
        name: " ⚡️ Formatting code with Ruff"
        args:
        - --fix

ci:
    autofix_commit_msg: 🎨 [pre-commit] Auto format
    autoupdate_commit_msg: ⬆ [pre-commit] pre-commit auto update