site_name: {{cookiecutter.package_name_stylized}}
site_description: {{cookiecutter.short_description}}
site_author: {{cookiecutter.author_name}}
site_url: https://{{cookiecutter.github_organization_name.lower()}}.github.io/{{cookiecutter.package_name}}
repo_name: {{cookiecutter.github_organization_name}}/{{cookiecutter.package_name}}
repo_url: https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_name}}
edit_uri: "edit/main/docs/"
copyright: Copyright &copy; {% now 'local', '%Y' %} {{cookiecutter.author_name}}

theme:
  name: "material"
  favicon: assets/logo.svg
  logo: assets/logo.svg
  # icon:
  #   logo: material/microscope
  language: en
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# https://fontawesome.com/icons/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
nav:
  - About:
    - About: index.md
    - Usage: usage.md
    - Development: development.md
  - Code reference:
      - Api: Api.md
  - Issues: https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_name}}/issues" target="_blank

plugins:
# - admonition
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        options:
          show_source: true
    # custom_templates: templates

watch:
  - src
  - docs

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - smarty


extra_css:
  - assets/custom.css

extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.package_name}}
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_organization_name}}
    # - icon: fontawesome/brands/docker
    #   link: https://github.com/orgs/{{cookiecutter.github_organization_name}}/packages
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/um_ids
