site_name: {{cookiecutter.package_name_stylized}}
site_description: {{cookiecutter.short_description}}
site_author: {{cookiecutter.author_name}}
site_url: https://{{cookiecutter.github_organization_name.lower()}}.github.io/{{cookiecutter.package_slug}}
repo_name: {{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}
repo_url: https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}
edit_uri: "edit/main/docs/"
copyright: Copyright &copy; {{date.today().year}} {{cookiecutter.author_name}}

theme:
  name: "material"
  favicon: assets/logo.png
  logo: assets/logo.png
  # icon:
  #   logo: material/microscope
  language: en
  # https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#primary-color
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.code.annotate
    # - content.tabs.link
    # - header.autohide
    # - navigation.expand
    - navigation.indexes
    # - navigation.instant
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow

# https://fontawesome.com/icons/
# https://squidfunk.github.io/mkdocs-material/reference/icons-emojis/
nav:
  - About:
    - About: index.md
    - Usage: usage.md
    - Development: development.md
  - Code reference:
      - "<span><i class='fa-solid fa-flask'></i>&nbsp;&nbsp;API</span>": API.md
      # - "<span><i class='fa-solid fa-vial-circle-check'></i>&nbsp;&nbsp;FairTestEvaluation</span>": FairTestEvaluation.md
      # - "<span><i class='fa-solid fa-flask-vial'></i>&nbsp;&nbsp;FairTestAPI</span>": FairTestAPI.md
  - "<span>Issues&nbsp;&nbsp;<i class='fa-solid fa-arrow-up-right-from-square'></i></span>": https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}/issues" target="_blank

plugins:
# - admonition
- search
- autorefs
- mkdocstrings:
    default_handler: python
    handlers:
      python:
        rendering:
          show_source: true
    # custom_templates: templates
    watch:
      - fair_test

# https://squidfunk.github.io/mkdocs-material/reference/admonitions/#supported-types
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - smarty


extra_css:
  - assets/custom.css

extra_javascript:
  - assets/fontawesome.min.js
  - assets/solid.min.js


extra:
  social:
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/{{cookiecutter.package_slug}}
    - icon: fontawesome/brands/github
      link: https://github.com/{{cookiecutter.github_organization_name}}
    # - icon: fontawesome/brands/docker
    #   link: https://github.com/orgs/MaastrichtU-IDS/packages
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/um_ids