[tool.poetry]
name = "{{cookiecutter.package_slug}}"
version = "0.0.1"
description = "{{cookiecutter.short_description}}"
authors = ["{{cookiecutter.author_name}} <{{cookiecutter.author_email}}>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}"
repository = "https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}"
keywords = [  ]
include = [
    "LICENSE",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

{% if cookiecutter.command_line_interface|lower != "false" %}
[tool.poetry.scripts]
{{cookiecutter.package_slug}} = "{{cookiecutter.package_name}}.__main__:cli"
{% endif %}


[tool.poetry.dependencies]
python = ">=3.8,<3.11"
{% if cookiecutter.command_line_interface|lower != "false" %}
typer = "^0.6.0"
{% endif %}


[tool.poetry.dev-dependencies]
mypy = "^0.770"
black = "^19.10b0"
isort = "^4.3.21"
autoflake = "^1.3.1"
flake8 = "^3.7.9"
pytest = "^6.2.5"
pytest-cov = "^2.8.1"
{% if cookiecutter.documentation_website|lower != "false" %}
# Dependencies for docs are also in docs/requirements.txt for the GitHub Action to publish-docs
jinja2= "3.0.3"
mkdocstrings = {extras = ["python"], version = "^0.19.0"}
mkdocs-material = "^8.2.7"
{% endif %}


[tool.poetry.urls]
"Bug Tracker" = "https://github.com/{{cookiecutter.github_organization_name}}/{{cookiecutter.package_slug}}/issues"


[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
